[project]
name = "playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pydantic-ai>=1.106.0",
    "python-dotenv>=1.2.2",
    "strands-agents>=1.42.0",
    "strands-agents-tools>=0.8.0",
    "z-grc @/Users/samrat/Projects/c-z-grc/packages/python/dist/z_grc-0.1.0-cp312-cp312-macosx_11_0_arm64.whl",
]
